### ISSUE TITLE
Operator: reload button

### ISSUE THREAD

**Issue by wilkinsmt1** [wilkinsmt1/CPTS-323-SAD-Project#11]
As an Operator I need a reload button because I need to reset the missile count once the launcher runs out of missiles.

**Comment by annacal** [comment]
#11 Reload button

Pre-Condition: 
The launcher will fire all of its missiles, and the number of targets that can be hit will be limited.

Normal Steps:
Action 1. Add a reload button.
Action 2. Add a continue with game button.
Action 3. The user will press the reload button after firing all of the missiles. 
Action 4. The game will be paused automatically.
Action 5. The count for the number of missiles available to fire will be reset to maximum.
Action 6. The user will reload the missiles onto the launcher.
Action 7. The user will be prompted to recalibrate the launcher.
Action 8. The operator will recalibrate the launcher.
Action 9. The program will confirm the calibration.
Action 10. The user will test the calibration if possible using coordinates that do not contain any target, and checked for accuracy.
Action 11. When ready, the operator will press the "continue with game" button.
Action 12. The game will continue; displaying coordinates, number of missiles available, etc.

Alternative Steps:
Action 1. The reload button can be pressed at any time to reset the launcher settings.

Post-Condition:
The launcher can be reloaded when needed.

**Comment by wilkinsmt1** [comment]
Reload button has been added, I replaced it with the remove targets button that was initially on the GUI.
