### ISSUE TITLE
Operator: manual mode

### ISSUE THREAD

**Issue by wilkinsmt1** [wilkinsmt1/CPTS-323-SAD-Project#12]
As an operator I need to create a manual mode because I need to test and calibrate the missile launcher.

**Comment by annacal** [comment]
#12 Manual mode

Pre-Condition: 
The game is set to be mostly automated.

Normal Steps:
Action 1. Add a menu selection for manual mode.
Action 2. When the operator selects manual mode, the game will display coordinates from the server, but the operator will enter the coordinates manually to set the launcher.
Action 3. The launcher will launch one missile at a time.
Action 4. The enemy targets that are still existing will then be displayed with their coordinates.
Action 5. A button to "quit" the game will be added so the operator can exit the game when finished.
Action 6. The operator will continue to enter given coordinates to launcher and fire the missile until either all enemy targets are eliminated, the timer runs out, or the operator exits the game. 

Alternative Steps:
Action 1. each step of the program can be manual.

Post-Condition:
When the operator selects "manual mode", the game will be manual for entering coordinates, and only one missile will be fired at a time.

**Comment by wilkinsmt1** [comment]
For Project Three we need buttons that control the missile launcher manually.
Controls include: Up, Down, Left, Right, and Fire.

**Comment by wilkinsmt1** [comment]
The buttons that control the missile launcher manually have been implemented. When the user presses the up/down/left/right buttons the missile launcher moves in that direction by about 5 degrees.
The fire button has also been implemented, when the user presses the fire button a missile is fired and the missile count display is updated.
