### ISSUE TITLE
Client: automatic mode/Strategy

### ISSUE THREAD

**Issue by wilkinsmt1** [wilkinsmt1/CPTS-323-SAD-Project#13]
As a client I need an automatic mode/strategy so I can compete and win the competition.

**Comment by annacal** [comment]
#13 Automatic mode

Pre-Condition:
The game is fully manual; the camera must be turned on manually, the information from the server must be entered into the game application, the operator must push "launch" to launch the missile, the operator must push a button to determine which enemy targets still exist, and the program must be closed manually.  

Normal Steps:
Action 1. Set the camera to start when the program begins.
Action 2. The first screen the operator will see is the list of games, including one game that is a file on the PC, and also an option to calibrate will be on the same page. 
Action 3. Add a manual option either on the menu with the lists of games, or the option after beginning any game.
Action 3. When a game starts, the coordinates will be loaded to the missile launcher from the server automatically, unless a manual option is selected.
Action 4. When the missile launcher is ready to fire, a prompt will display to either "fire the missile" or "change settings".
Action 5. Prompt to either reload the launcher or exit the game.  

Alternative Steps:
Actions 1-3. same
Action 4. When the missile launcher is ready to fire, a prompt will display to either "fire the missile", "exit", "change settings", and/or "calibrate".  
Action 5. Prompt to either reload the launcher or exit the game.  

Other Alternative Steps:
Actions 1-2. same
Actions 3. When a game starts, the coordinates for all of the targets will be loaded to the missile launcher from the server automatically, unless a manual option is selected.
Action 4. Fire all the missiles automatically without a prompt, one after another to hit each target.
Action 5. Prompt to either reload the launcher or exit the game.  

Post-Condition:
When the user turns on the PC, monitor, and opens the program, the program will be as automatic as possible.

**Comment by wilkinsmt1** [comment]
For Project 4 our application must be able to eliminate targets.
From the Project PDF:
3. Target Elimination
a. Kill All Enemies – eliminates all enemies
b. Kill All Friends – eliminates all friends
c. Kill All Targets – eliminates all targets

**Comment by wilkinsmt1** [comment]
While I do not think we will implement an 'Auto' button, once our application is able to communicate with the server and retrieve games that can be selected, I think 'Auto mode' will be completed. I think you can debate whether or not the Target Elimination features are 'Auto mode', so I will just move this to the next iteration.

**Comment by wilkinsmt1** [comment]
Just for clarity, "automatic mode" is our strategy.
