### ISSUE TITLE
Operator: start button

### ISSUE THREAD

**Issue by wilkinsmt1** [wilkinsmt1/CPTS-323-SAD-Project#14]
As an Operator I need a start button because I want to tell the program when to initiate a new game.

**Comment by annacal** [comment]
#14 Start button

Pre-Condition:
The operator cannot start the game.

Normal Steps:
Action 1. Add a "start" button.
Action 2. When the operator selects "start", then the game will begin.

Alternative Steps:
Action 1. Add a "start" button.
Action 2. When the operator selects "start", then a menu of options is displayed.

Post-Condition:
The operator can start the game.

**Comment by wilkinsmt1** [comment]
For Project 5 our application needs to be able to start a game

From the Project PDF:
2. Game Start (30 points)
a. From a drop down list the user should be able to select a game name and press start.
b. When started, the application should eliminate all foe targets only.

**Comment by wilkinsmt1** [comment]
Right now our application can start a game, however our strategy on killing targets needs work.
