### ISSUE TITLE
Operator: stop button

### ISSUE THREAD

**Issue by wilkinsmt1** [wilkinsmt1/CPTS-323-SAD-Project#15]
As an Operator I need a stop button because I want to tell the program when to exit game mode.

**Comment by annacal** [comment]
#15 Stop button

Pre-Condition:
The operator cannot stop the game once it has begun.

Normal Steps:
Action 1. Add a button to "quit" the game.
Action 2. When the button is pressed, prompt the user as "Would you like to quit the game? yes/no ".
Action 3. If the operator selects yes, then exit the game. 
Action 4. If the operator selects no, then continue the game.

Alternative Steps:
Action 1. Do not add a stop button.
Action 2. Add a reset button for the game, and begin a new game.

Post-Condition:
The operator can stop the game after starting, or reset to a new game.

**Comment by wilkinsmt1** [comment]
Our application has the ability to stop a game, however I think we want to make our application automatically stop the game once all foe targets have been eliminated.
