### ISSUE TITLE
Client: access to twitter

### ISSUE THREAD

**Issue by wilkinsmt1** [wilkinsmt1/CPTS-323-SAD-Project#16]
As a Client I need access to Twitter because I want to tweet messages related to games being played.

**Comment by annacal** [comment]
#16 Access to twitter

Pre-Condition:
The operator has no access to twitter.  

Normal Steps:
Action 1. Set up a twitter account for the project.
Action 2. Send a tweet using the new account.
Action 3. Find out how to add twitter to the game.
Action 4. Add twitter to the game.  

Alternative Steps:
Action 1. Do not use twitter.
Action 2. Use an alternative method of communication such as email.  

Post-Condition:
The operator has access to twitter, or has another form of communication.

**Comment by wilkinsmt1** [comment]
I don't think we will be able to implement this by the time of the competition, I also do not think that it is required to implement this.
