### ISSUE TITLE
Client: access to game server

### ISSUE THREAD

**Issue by wilkinsmt1** [wilkinsmt1/CPTS-323-SAD-Project#17]
As a Client I need access to the game server so I can load game files and target files from the sever.

**Comment by annacal** [comment]
#17 Access to game server

Pre-Condition:
The operator cannot load game files and target files from the sever.  

Normal Steps:
Action 1. Get the web address for the server.
Action 2. Download 6 games to the PC.
Action 3. Get instructions about how to load target files from the server.
Action 4. Load target files from the server.  

Alternative Steps:
Action 1. If target files cannot be loaded from the server, then create game files to use from the PC. 
Action 2. Then add coordinates to the games manually. 

Post-Condition:
The operator can either load game files and target files from the server, or has alternative game files that can be used.
