### ISSUE TITLE
Operator: game timer

### ISSUE THREAD

**Issue by wilkinsmt1** [wilkinsmt1/CPTS-323-SAD-Project#18]
As an Operator I need a game timer so I know how long a game has been played for.

**Comment by annacal** [comment]
#18 Game Timer

Pre-Condition:
The game will not end until all enemy targets are hit.

Normal Steps:
Action 1. Program the timer to begin automatically when the game starts.

Alternative Steps:
Action 1. Do not add a timer.
Action 2. or, add a timer and off switch for the timer.

Post-Condition:
The game will end when the timer ends.

**Comment by wilkinsmt1** [comment]
I think we would want to implement a Game Timer, so that our application will stop a game after a certain period of time has elapsed, for example 60 seconds.

**Comment by wilkinsmt1** [comment]
We don't need a game timer
