### ISSUE TITLE
Client: internet connectivity

### ISSUE THREAD

**Issue by wilkinsmt1** [wilkinsmt1/CPTS-323-SAD-Project#19]
As a client I need internet connectivity in order to communicate with the game server and Twitter.

**Comment by annacal** [comment]
#19 Internet Connectivity

Pre-Condition:
The program cannot connect to the internet.

Normal Steps:
Action 1. connect to the internet via wifi. 

Alternative Steps:
Action 1. if internet is not available, use file/game created for this.  

Post-Condition:
The program can connect to the internet.

**Comment by wilkinsmt1** [comment]
While our application is not able to connect to Twitter, it is able to connect to the GameServer and successfully retrieve game and target info. So this issue is closed.
