### ISSUE TITLE
Operator: turret control

### ISSUE THREAD

**Issue by wilkinsmt1** [wilkinsmt1/CPTS-323-SAD-Project#20]
As an operator I need turret control because I want to be able to move the turret up, down, left, and right.

**Comment by annacal** [comment]
#20 Turret Control Buttons

Pre-Condition:
The operator cannot control movement of the turret.

Normal Steps:
Action 1. find out what turret control buttons are available
Action 2. Add turret control buttons
Action 3. find out how to use the turret control buttons

Alternative Steps:
Action 1. Do not use turret control buttons.

Post-Condition:
The operator can control the movement of the turret.

**Comment by wilkinsmt1** [comment]
Operator is able to have turret control in the SADCL, this was achieved by controlling the missile launcher by adapting code from MissileLauncher.cs

So this one is closed!
