### ISSUE TITLE
Operator: GUI exit

### ISSUE THREAD

**Issue by ghost** [wilkinsmt1/CPTS-323-SAD-Project#21]
As an Operator I want to exit the GUI because I want to stop using the missile launcher program.

**Comment by annacal** [comment]
#21 GUI Exit

Pre-Condition:
The GUI is running.  

Normal Steps:
Action 1. create a way for the operator to make a selection to exit the GUI.
Action 2. when the operator selects "Exit GUI", the program exits.  

Alternative Steps:
Action 1. Enable an exit button for each manual step in the game.  

Post-Condition:
The GUI is not running.

**Comment by wilkinsmt1** [comment]
The GUI has an exit button that closes the program so, this issue is closed.
