### ISSUE TITLE
Operator: GUI game list

### ISSUE THREAD

**Issue by ghost** [wilkinsmt1/CPTS-323-SAD-Project#22]
As an Operator I want a game list because I want to be able to choose what sort of game I want to play.

**Comment by annacal** [comment]
#22 GUI Game List  
Pre-Condition:
The games are not listed.  
Normal Steps:
Action 1. get the list of games from online: tech tools; dream spark  
Alternative Steps:
Action 1. create a file/game for use without server  
Post-Condition:
The games are listed.

**Comment by wilkinsmt1** [comment]
Our application is able to retrieve and display a game list from the GameServer, it is also able to start a game based on which game was selected. So this issue is closed.
