### ISSUE TITLE
Operator: GUI OK

### ISSUE THREAD

**Issue by ghost** [wilkinsmt1/CPTS-323-SAD-Project#23]
As an Operator I want to click OK at the start because I want to select the game in the game list I want.

**Comment by ghost** [comment]
#23 GUI OK

Pre-Condition:
A game is selected

Normal Steps:
Action 1. Press OK

Alternative Steps:
Action 1. Load game automatically

Post-Condition:
The game is loaded

**Comment by wilkinsmt1** [comment]
Our GUI does not have an OK button for starting a game, it does have a Start button which starts a game however. So this issue is closed.
