### ISSUE TITLE
Operator: GUI Settings

### ISSUE THREAD

**Issue by ghost** [wilkinsmt1/CPTS-323-SAD-Project#24]
As an Operator I want settings because I want to change option on how I play.

**Comment by ghost** [comment]
#24 GUI Settings

Pre-Condition:
At the game list.

Normal Steps:
Action 1. Press the Settings button.

Alternative Steps:
Action 1. None

Post-Condition:
The settings for the game are displayed.

**Comment by wilkinsmt1** [comment]
I think this feature is related to the Game Integration milestone rather than the GUI milestone, so i'm moving this from Iteration 3 to Iteration 5.

**Comment by wilkinsmt1** [comment]
I don't think our GUI needs a settings button, so I'm dropping it from the milestone.
