### ISSUE TITLE
Operator: GUI Auto

### ISSUE THREAD

**Issue by ghost** [wilkinsmt1/CPTS-323-SAD-Project#25]
As an Operator I want an Auto button because I want to have the missile launcher to fire automatically.

**Comment by ghost** [comment]
#25 GUI Auto

Pre-Condition:
At the intro screen.

Normal Steps:
Action 1. Press the Auto button to arrive at the game list.

Alternative Steps:
Action 1. None.

Post-Condition:
At the  game list for Auto.

**Comment by wilkinsmt1** [comment]
For Project Three we just need to implement Manual mode so I moved this to a later Milestone.

**Comment by wilkinsmt1** [comment]
While I do not think we will implement an 'Auto' button, once our application is able to communicate with the server and retrieve games that can be selected, I think 'Auto mode' will be completed. So I am moving this to the next iteration.

**Comment by wilkinsmt1** [comment]
Instead of an auto button. this will be implemented as a strategy.
