### ISSUE TITLE
Operator: GUI Time

### ISSUE THREAD

**Issue by ghost** [wilkinsmt1/CPTS-323-SAD-Project#26]
As an Operator I want a time function because I want to know how long the launcher is able to fire.

**Comment by ghost** [comment]
#26 GUI Time

Pre-Condition:
The time is not counting down.

Normal Steps:
Action 1. Begin the game.

Alternative Steps:
Action 1. Fire the first shot.

Post-Condition:
The time is counting down.

**Comment by wilkinsmt1** [comment]
We don't need a time function.
