### ISSUE TITLE
Operator: GUI Manual

### ISSUE THREAD

**Issue by ghost** [wilkinsmt1/CPTS-323-SAD-Project#27]
As an Operator I want a Manual button because I want to be able to manually aim my missile launcher at targets.

**Comment by ghost** [comment]
#27 GUI Manual

Pre-Condition:
The game is at the intro screen.

Normal Steps:
Action 1. Press the Manual button.

Alternative Steps:
Action 1. None.

Post-Condition:
You are in Manual mode and can move the launcher manually.

**Comment by wilkinsmt1** [comment]
In Project Three manual mode will be implemented. We need to implement buttons that control the missile launcher manually.
Controls include: Up, Down, Left, Right, and Fire.

**Comment by wilkinsmt1** [comment]
The GUI has buttons to manually control the missile launcher. The up/down/left/right and fire buttons have been implemented.
