### ISSUE TITLE
Operator: GUI Targets

### ISSUE THREAD

**Issue by ghost** [wilkinsmt1/CPTS-323-SAD-Project#28]
As an Operator I want targets to be listed because I want to know the status on all the current targets.

**Comment by ghost** [comment]
#28 GUI Targets

Pre-Condition:
The game is either at the intro screen or the game list.

Normal Steps:
Action 1. Choose a game to play.

Alternative Steps:
Action 1. Go to the Manual screen.

Post-Condition:
The targets and their statuses are listed.

**Comment by annacal** [comment]
A 'Target Display' button has been added that will display targets and target data using a json file. 
The targets and their statuses are listed.

**Comment by wilkinsmt1** [comment]
The target display list box has been implemented with a TargetViewModel. When a file is loaded the targets are displayed in the Target list box, with the values Name, Friend, X, Y, Z, Points, Flash Rate, Spawn Rate, Can Swap Sides, and Alive.
