### ISSUE TITLE
Operator: GUI Begin

### ISSUE THREAD

**Issue by ghost** [wilkinsmt1/CPTS-323-SAD-Project#29]
As an Operator I want a Begin button because I want to choose when exactly to start my automatic game.

**Comment by ghost** [comment]
#29 GUI Begin

Pre-Condition:
The game has not started.

Normal Steps:
Action 1. Press the Begin button to start the game.

Alternative Steps:
Action 1. None.

Post-Condition:
The game will now begin properly.

**Comment by wilkinsmt1** [comment]
While our application does not have a Begin button, it has a start button which starts a game. So this issue is closed.
