### ISSUE TITLE
Operator: GUI Video

### ISSUE THREAD

**Issue by ghost** [wilkinsmt1/CPTS-323-SAD-Project#30]
As an Operator I want a Live Video because I want to be able to see what my launcher is aiming at.

**Comment by ghost** [comment]
#30 GUI Video

Pre-Condition:
No live video is displayed/Live video is on.

Normal Steps:
Action 1. Press the Live Video button to see the live feed.

Alternative Steps:
Action 1. Press it again to turn off live feed.

Post-Condition:
Live video is on/No live video is displayed.

**Comment by wilkinsmt1** [comment]
The GUI must display a live video and have controls to start/stop the camera. For Project 3 we have to implement the ability for the camera to take and display a picture.

**Comment by wilkinsmt1** [comment]
Live video button has been successfully implemented.
