### ISSUE TITLE
Operator: GUI Fire

### ISSUE THREAD

**Issue by ghost** [wilkinsmt1/CPTS-323-SAD-Project#31]
As an Operator I want a Fire button because I want to be fire the missile at targets in manual mode.

**Comment by ghost** [comment]
#31 GUI fire

Pre-Condition:
The launcher has not fired a missile.

Normal Steps:
Action 1. Press the button to fire a missile.

Alternative Steps:
Action 1. Press it again to fire more missiles.

Post-Condition:
A missile has been fired.

**Comment by wilkinsmt1** [comment]
The fire button has been implemented. When the fire button is clicked the missile launcher fires a missile and the missile count display is updated.
