### ISSUE TITLE
Operator: GUI Arrows

### ISSUE THREAD

**Issue by ghost** [wilkinsmt1/CPTS-323-SAD-Project#32]
As an Operator I want Arrow buttons because I want to move the launcher left or right to hit targets manually.

**Comment by ghost** [comment]
#31 GUI Arrows

Pre-Condition:
The launcher has not moved from its original position.

Normal Steps:
Action 1. Press the left arrow to move the launcher left.

Alternative Steps:
Action 1. Press the right arrow to move the launcher right.

Post-Condition:
The launcher has moved in the desired direction.

**Comment by wilkinsmt1** [comment]
For Project Three we need buttons that control the missile launcher manually.
Controls include: Up, Down, Left, Right, and Fire.

**Comment by wilkinsmt1** [comment]
The "arrow" buttons have been added to the GUI and implemented. The buttons control the missile launcher by moving it five degrees in the left/right/up or down direction. Instead of having arrows on the buttons we have decided to just have the name of the direction on the buttons.
