### ISSUE TITLE
Wireframe01

### ISSUE THREAD

**Issue by ghost** [wilkinsmt1/CPTS-323-SAD-Project#33]
![wireframe01wip2](https://cloud.githubusercontent.com/assets/10702857/6067210/b2878b98-ad27-11e4-83b5-3b8b78c6c940.png)

**Comment by annacal** [comment]
#33 Wireframe 01

Pre-Condition:
The Start A Game Wireframe page does not exist.

Normal Steps:
Action 1. Create a interface with "Do you want to start a game?
Action 2. Add an Auto button.
Action 3. Add a Manual button.
Action 4. Add a Cancel button.

Alternative Steps:
Action 1. To streamline the program, find a way to include these buttons to another already existing page.

Post-Condition:
The Start A Game Wireframe page does exist.

**Comment by wilkinsmt1** [comment]
Our application does not have a start game window, but it does have the features to start a game. So this issue is closed.
