### ISSUE TITLE
Wireframe02

### ISSUE THREAD

**Issue by ghost** [wilkinsmt1/CPTS-323-SAD-Project#34]
![wireframe02wip2](https://cloud.githubusercontent.com/assets/10702857/6067220/cb5d3ec4-ad27-11e4-8b1d-fa8b3ad89662.png)

**Comment by annacal** [comment]
#34 Wireframe 02

Pre-Condition:
The Game Selection List Wireframe page does not exist.

Normal Steps:
Action 1. Create a interface with a list of games.
Action 2. Add a Settings button.
Action 3. Add an Ok button.
Action 4. Add a Cancel button.

Alternative Steps:
Action 1-4. same
Action 5. Add a button to select a game file from the PC.

Post-Condition:
The Game Selection List Wireframe page does exist.

**Comment by wilkinsmt1** [comment]
Our GUI has a drop down menu that displays a game list retrieved from the GameServer, and has the ability to select and start a game. So this issue is closed.
