### ISSUE TITLE
Wireframe 03

### ISSUE THREAD

**Issue by ghost** [wilkinsmt1/CPTS-323-SAD-Project#35]
![wireframe03](https://cloud.githubusercontent.com/assets/10702857/6067229/df5f4836-ad27-11e4-9d0a-05cd5627b529.png)

**Comment by annacal** [comment]
#35 Wireframe 03

Pre-Condition:
The Auto Wireframe page does not exist.

Normal Steps:
Action 1. Create a interface with targets listed as friend or foe.
Action 2. Add a Begin button.
Action 3. Add a Cancel button.
Action 4. Add live video interface.
Action 5. Add time left information.
Action 6. Add X's to every target initially.
Action 7. Add a check mark if the foe target is eliminated.

Alternative Steps:
Action 1. Use a less graphical approach to the user interface.

Post-Condition:
The Auto Wireframe page does exist.

**Comment by wilkinsmt1** [comment]
Once our application is able to communicate with the server and retrieve games that can be selected, I think 'Auto mode' will be completed. So I am moving this to the next iteration.

**Comment by wilkinsmt1** [comment]
So far our application does not have a game timer yet, so this is not closed yet.
