### ISSUE TITLE
Wireframe 04

### ISSUE THREAD

**Issue by ghost** [wilkinsmt1/CPTS-323-SAD-Project#36]
![wireframe04](https://cloud.githubusercontent.com/assets/10702857/6067236/ead014fc-ad27-11e4-97dc-e55851dec4bb.png)

**Comment by annacal** [comment]
#36 Wireframe 04

Pre-Condition:
The Manual Wireframe page does not exist.

Normal Steps:
Action 1. Create a interface with targets listed as friend or foe.
Action 2. Add a fire button.
Action 3. Add a cancel button.
Action 4. Add live video interface.
Action 5. Add time left information.
Action 6. Add X's to every target initially.
Action 7. Add a check mark if the foe target is eliminated.

Alternative Steps:
Action 1. Use a less graphical approach to the user interface.

Post-Condition:
The Manual Wireframe page does exist.

**Comment by wilkinsmt1** [comment]
GUI has been created based on this Wireframe.
