### ISSUE TITLE
testing of the TargetPositioning.cs  Class 

### ISSUE THREAD

**Issue by annacal** [wilkinsmt1/CPTS-323-SAD-Project#39]

**Comment by annacal** [comment]
#39 testing of the TargetPositioning.cs Class 
Pre-Condition:
The TargetPositioning.cs Class has not been tested fully. It has been only minimally tested.
Normal Steps:
Action 1: testing various data; compare with expected results.
Action 2: also, currently there is no error checking; will add that.
Post-Condition:
The TargetPositioning.cs file/Class will be more reliable.

**Comment by annacal** [comment]
The class is currently at the github account for annacal, in a TargetPositioning.cs repository.

**Comment by wilkinsmt1** [comment]
TargetPositioning.cs has been edited and tested so this is complete!
