### ISSUE TITLE
command line application 

### ISSUE THREAD

**Issue by annacal** [wilkinsmt1/CPTS-323-SAD-Project#40]
When the program has finished loading the system should start accepting user commands

User Prompt: 
The user should know they are able to input commands via a prompt:
    commandlinePrompt>  SadCL
    System Loaded 
    Ready to Fire Ze Missiles
     >

Command line application:
1. FIRE
a. This command will cause the missile launcher to immediately fire!
b. If no missiles are left, it should display a message to the Captain: “I just can’t do it
cap’tin, we just don’t have tha power”
2. MOVE phi theta
a. This command should move the missile launcher to the phi, theta position.
b. Phi theta are separated by spaces and should be double amounts
3. MOVEBY phi theta
a. This command should move the missile launcher by an phi, theta amount
b. Phi theta are separated by spaces and should be double amounts
4. RELOAD
a. This command should reset the missile count of the launcher
5. LOAD <filepath>
a. This command should load a target file at the file path specified.
b. If the file does not exist display a user message: “no file exists”
c. If the file does not exist display a user message: “ya, that’s just a bad file”
d. If the file does exist display a user message: “argghh argghh new targets in sight”
6. SCOUNDRELS
a. This command should display a list of enemy targets
Target: Buddy
Friend: No He’s a scoundrel with a clever disguise
Position: x=50, y=23, z=34
Points: 100
Status: At Large
7. FRIENDS
a. This command should display a list of friend targets
Target: Buddy
Friend: One of us
Position: x=50, y=23, z=34
Points: 100
Status: At Large
8. KILL targetName
a. This command should fire at the target specified. If it is a friend it must display:
“Sorry Captain, we don’t permit friendly fire, yar”
9. STATUS
a. This command should display the name of the missile launcher, how many missiles are
left to fire, and the missile capacity of the launcher:
Launcher: Poseidon
Missiles: 1 of 4 remain

**Comment by wilkinsmt1** [comment]
SADCL is almost complete.
We need a singleton TargetManager.

Missile launcher can move but it has not been implemented with the targetpositioning.cs class, I also need to figure out how to convert phi theta to the missilelauncher.cs units.

All commands are finished except KILL which uses the TargetManager, and parts of SCOUNDRELS and FRIENDS which also use it.

**Comment by annacal** [comment]
what are the units of missilelauncher.cs?  The unit types may not be
important, because the length of one unit is converted to degrees using
trig functions and fractions, so the units shouldn't make a difference.
 the targetpositioning.cs class takes as argumetnts  double x, double y
maybe it needs a z value. I'll look at that.

**Comment by annacal** [comment]
if you know what the arguments need to be exactly for the whatever is using
it, and what needs to come out, let me know when you get a chance.

**Comment by wilkinsmt1** [comment]
Command line program is finished.
