### ISSUE TITLE
create an XML text file

### ISSUE THREAD

**Issue by annacal** [wilkinsmt1/CPTS-323-SAD-Project#41]
Find out how to change this to an XML text file:

[Target]
Name=TargetOne
X=50
Y=20
Z=10
Friend=true
Points=50
FlashRate=-1        # this means the target is constantly on
SpawnRate=4
CanSwapSidesWhenHit=false

[Target]
Name=TargetTwo
X=50
Y=60
Z=10
Friend=false
Points=50
FlashRate=-1  
SpawnRate=4
CanSwapSidesWhenHit=false

[Target]
Name=Enemy
X=50
Y=20
Z=00
Friend=false
Points=500
FlashRate=100       # this means the target is on for 100 milliseconds
SpawnRate=4
CanSwapSidesWhenHit=false

[Target]
Name=TargetX
X=50
Y=20
Z=10
Friend=true
Points=50
FlashRate=-1        # this means the target is constantly on
SpawnRate=4
CanSwapSidesWhenHit=false

[Target]
Name=TargetY
X=503
Y=602
Z=102
Friend=false
Points=50
FlashRate=-1  
SpawnRate=4
CanSwapSidesWhenHit=false

[Target]
Name=EnemyZ
X=570
Y=230
Z=004
Friend=false
Points=500
FlashRate=1000  
SpawnRate=4

CanSwapSidesWhenHit=false

**Comment by brianlamarche** [comment]
Hint, use serialization.  I would suggest Json actually. ;)

We did this in class.
