### ISSUE TITLE
how factory, adapter, and IMissile Interface work together.

### ISSUE THREAD

**Issue by annacal** [wilkinsmt1/CPTS-323-SAD-Project#43]
if working on this, add name to this issue

**Comment by wilkinsmt1** [comment]
Figured this one out,
Factory is called in main and creates a DC or Mock missile launcher.
When a DC is created a controller and controller.Launcher (which is a MissileLauncherAdapter type) is created.
When a user enters a command, main calls DC methods, which call controller methods, which call MissileLauncherAdapter methods, which then calls methods from MissileLauncher.cs.

So this one is closed!
