### ISSUE TITLE
Scoundrels, Friends, and Kill commands (using IsFriend function in the INI file reader)

### ISSUE THREAD

**Issue by annacal** [wilkinsmt1/CPTS-323-SAD-Project#49]
add name if working on this

**Comment by wilkinsmt1** [comment]
Scoundrels and Friends commands are almost complete, they just need status information from the TargetManager.

The Kill command has not been implemented yet.

**Comment by wilkinsmt1** [comment]
All three commands have been implemented and tested, and they are complete.
