### ISSUE TITLE
command interface in the main function

### ISSUE THREAD

**Issue by annacal** [wilkinsmt1/CPTS-323-SAD-Project#50]
add name if working on this

**Comment by wilkinsmt1** [comment]
Command line interface is almost done, all commands have been implemented except Kill.

However, the Scoundrels and Friends commands need status information from the TargetManager.
For the kill command once executed, targets need to be removed from the TargetManager list.
Kill command has not been implemented at all.

**Comment by wilkinsmt1** [comment]
Scoundrels, Friends, and Kill commands are completed.
The command interface in main has been finished.
Hooray!
