### ISSUE TITLE
Milestone Planning, Issue Refinement, and Execution section of project 2 pdf (page 4).

### ISSUE THREAD

**Issue by annacal** [wilkinsmt1/CPTS-323-SAD-Project#51]
add name if working on this

**Comment by wilkinsmt1** [comment]
User stories related to this milestone and the next have been examined.
Irrelevant user stories have been moved to the next milestone.
Relevant user stores have been moved from the next milestone into this one.
Stories have been converted in to tasks and broken up.
Additional tasks not predicted by the user story have been added.
Finished tasks have been closed.
