### ISSUE TITLE
Project 2: Fix Friend or Foe Tagging

### ISSUE THREAD

**Issue by ghost** [wilkinsmt1/CPTS-323-SAD-Project#61]
Have the Kill command differentiate between friend or foe, as well as have friends and foes show up separately in the appropriate commands.

**Comment by wilkinsmt1** [comment]
I just tested it right now and found no problem with the kill command differentiating between friend and foe. Here's what I got when I tested it right now using the targets.ini file from Homework 1:
https://raw.githubusercontent.com/wilkinsmt1/CPTS-323-SAD-Project/master/Killcommand.png

The friends and scoundrels command are fixed, and I don't think the kill command was ever broken.
