### ISSUE TITLE
GUI select type of Missile Launcher

### ISSUE THREAD

**Issue by wilkinsmt1** [wilkinsmt1/CPTS-323-SAD-Project#69]
For Project Three we need to implement a way to select between a Dream Cheeky or Mock Missile Launcher.

**Comment by wilkinsmt1** [comment]
Missile launcher selector has been implemented in two buttons for Mock and Dream Cheeky

**Comment by annacal** [comment]
ok, the comboBox is working mostly.
I was going to submit it, but couldn't get it on time. I sent it in an
email anyway.
We can look at that later.
